# Generated by Django 4.0.4 on 2022-04-29 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_order_orderstatus_remove_productcart_cart_and_more'),
        ('products', '0002_category_sub_category_product_detail_product_label_and_more'),
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCart',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.orderstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.order'),
        ),
    ]
