# Generated by Django 4.0.4 on 2022-04-29 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_order_orderstatus_remove_productcart_cart_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.cart'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
