# Generated by Django 4.0.4 on 2022-05-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_image_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orderitem',
        ),
    ]
